---
format: 
  html:
    css: styles.css
---

# Assembling

In the first episode I showed a program listing in ARM assembly language, but I didn't
describe how to turn this into a runnable program.  There's no equivalent
to __debug.com__, so you have to type the program into a text file and then run a program
called an _assembler_.  According to computer lore, the term _assembler_ was coined in the 1950s
in the book __The Preparation of Programs for an Electronic Digital Computer__ by Maurice Wilkes, David Wheeler, and Stanley Gill, but it meant something more like a program that combined parts
of a program into one. Over time, the meaning evolved, and now an assembler is a tool that converts assembly language into machine instructions.

To run the assembler on Mac OS you'll need to install the XCode command line tools, part of Apple's development platform (or you can install the whole shebang from the App Store).  You only need the assembler (called __as__) and other compiler tools for now.  You can
get what you need with the command: 

```console
$ xcode-select --install
```

If this works, you should have the neccessary programs on your computer, though you might
have to set the PATH variable:

```
$ export PATH=/Library/Developer/CommandLineTools/usr/bin:$PATH
$ which as
/Library/Developer/CommandLineTools/usr/bin/as
```

Now you should be able to run the following commands to make an executable
program (assuming the source file is called beep.s):

```console
$ as -o beep.o beep.s
$ld -o beep beep.o -lSystem -syslibroot `xcrun -sdk macosx --show-sdk-path` \ 
-e _start -arch arm64
```

The first command runs the __as__ command to product an _object_ file.  We'll talk more about
that soon.  The __as__ program on MacOS is really just a shell script that runs the __clang__
compiler, part of the LLVM toolset [@LLVM:CGO04].

The second command, __ld__, creates the runnable program called __beep__.  The __ld__
program is called the _linker_[^1].  We'll talk more about this in the next episode, but the
basic idea is that to make an executable program we need to link our program's code to system
libraries (and sometimes other 3rd-party libraries).  Let's look at the arguments to this command:

```
-o beep
```
This specifies the executable program name.

```
-lSystem 
```
This says to use the _System_ directory to search for libraries to link.

```
-syslibroot `xcrun -sdk macosx --show-sdk-path`
```
Self-evident, so i'll skip this one.  Kidding!  The __-syslibroot__ option name is the root directory of the system library directories.  The next part is trickier though.
First you have to notice the backticks (__`__) around the __xcrun__ command, which means
"run this and then substitute the string you get back".  If we run the command by itself, 
it does something like this:

```console
$ xcrun -sdk macosx --show-sdk-path
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk
```

We could for instance list the contents of the directory with the command:

```console
$ ls `xcrun -sdk macosx --show-sdk-path`
Entitlements.plist	SDKSettings.plist	usr
SDKSettings.json	System
```

Back to the linker options:

```
-e _start
```
This tells the linker that the entry point is where the _start symbol is in our program.  Remember the
bit at the top of our first program that looked like this:

```asm
.global _start             // Provide program starting address to linker
.align 4

_start: 
```

Then the final option is:

```
-arch arm64
```
This tells the linker to produce a binary in the ARM 64 architecture format.  This is the default.

Note: quite often you _can_ get away with a much simpler version of the link command, for example
the following works for me for this program:

```console
ld -o beep beep.o -e _start
```

If the above commands work, you should now have a file called __beep__ that you can run (on MacOS,
for me anyway, the file already has the execute permission set).  Note though that if you do run
this the only way to terminate the program is with ^C.

As an alternative to running the program directly from the command line, you can also run it
with the __lldb__ debugger, which is part of the Xcode command line tools if you didn't already
have it.  This way you can stop the program before it goes into the infinite loop:

```console
$ lldb ./beep
(lldb) target create "./beep"
Current executable set to '/Dev/hdmcw/beep_4vr/beep' (arm64).
(lldb) b beep4eva
Breakpoint 1: where = beep`beep4eva, address = 0x0000000100003f9c
(lldb) run
Process 10410 launched: '//Dev/hdmcw/beep_4vr/beep' (arm64)
Process 10410 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
    frame #0: 0x0000000100003f9c beep`beep4eva
beep`beep4eva:
->  0x100003f9c <+0>:  mov    x0, #0x1 ; =1 
    0x100003fa0 <+4>:  adr    x1, 0x100003fb4 ; bel
    0x100003fa4 <+8>:  mov    x2, #0x1 ; =1 
    0x100003fa8 <+12>: mov    x16, #0x4 ; =4 
Target 0: (beep) stopped.
(lldb) 

```

One last detail.  You'll notice that the first part of most of the assembly language listings
here will have this directive:

```
.align 4
```

This tells the loader to align the instructions on a 4-byte boundary.  The _reason_ for doing
this will be more apparent after we cover the topic of memory, but for now know that you'll
probably need this directive to avoid errors when the program runs (you'll probably get
_Bus Error 100_, which has nothing to do with public transportation). This can be used in both the
code and data sections of our programs, but we'll go into that in more detail in later chapters.


[^1]: I assume it's not called __ln__ because that was already taken.  It's kind of like that [Demetri Martin joke about oranges and carrots](https://www.youtube.com/watch?v=NA6CaeSY8fs).
