---
format: 
  html:
    css: styles.css
---

# Instructions

When discussing registers, I mentioned that the actual machine instructions corresponding to each line
of assembly language are all 32 bits long.  This can be hard to grasp at first, because some
lines just look way more complicated and it seems like they should take more space.  But no,
an instruction like 

```
W0, #0x808, LSL #16
```

takes the same number of bits as

```
B loop
```

To manage this the ARM architecture defines a format (various formats) to fit everything necessary
into 32 bits.  This includes the operation itself (aka the _operation code_ or _opcode_[^1]), and operands
like memory addresses, literal values, and registers.  Taken together all of the different variations
of those 32 bits constitute the _instruction set_.

Let's take a look at some of the instructions from the programs we've already seen.  In the registers
episode we saw that the instruction for __MOVZ W0, #0x8405__ is the number

```
01010010100100001000000010100000  (0x529080a0)
```

The 32 bits for the instruction in this case need to encode (1) the opcode, (2) a register, and (3) the
"immediate" value __0x8405__.

The basic format of a MOV instruction is like this:

<table style="border: 1px solid black;text-align: center;white-space: nowrap;font-family:Courier New, monospace">
<thead style="font-weight: bold;padding: 1 5 1">
<tr>
<td> 31 </td> <td> 30_29 </td><td>28________23</td><td> 22_21 </td><td>20_____________________________5</td><td>4_______0</td>
</tr>
</thead>
<tbody>
<tr>
<td> sf </td> <td> opc </td><td>1 0 0 1 0 1</td><td> hw </td><td> imm16 </td><td>Rd</td>
</tr>
<tr>
<td> 0 </td> <td> 1 0 </td> <td>1 0 0 1 0 1</td><td> 00 </td><td> 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 </td><td>0 0 0 0 0</td>
</tr>
</tbody>
</table>

The _sf_ flag indicates either a 32- or 64-bit operation.  Here it's 0 because we're using the 32-bit
variant of the register, if we'd used the register __X0__ it would be _1_.  The next 8 bits are basically
the opcode for this instruction (this will change slightly for different variants of MOV).  The _hw_ here
stands for "halfword".  A halfword is 16 bits, or half of a 32-bit word, but the value of the bits in this
instruction are not super-relevant since we're moving an immediate value rather than a value at a memory
location.  The key parts here are the __imm16__ bits, which are
the value we're putting into the register and the __Rd__ bits, which indicate the register.  The register
value here is _00000_ since we're using the __W0__ register.  If it were _00001_ it would indicate the __W1__
register.


Let's look at another one.  The multiply instruction in our register program (__MUL W4, W3, W0__) has the
hex value __0x1b007c64__, or __00011011000000000111110001100100__ as 32-bit binary.  The __MUL__ instruction
is actually an alias for a version of the __MADD__ instruction (multiply and add), which does "multiply the values in two registers then add the value of another register".  The bits for this instruction break down
thusly:


<table style="border: 1px solid black;text-align: center;white-space: nowrap;; font-family: Courier New,monospace">
<thead style="font-weight: bold;padding: 1 5 1">
<tr>
<td> 31 </td> <td> 30-29 </td><td>28_______24</td><td> 23 21 </td><td>20_______16</td><td>15</td><td>14______10</td><td>9______5</td><td>4______0</td>
</tr>
</thead>
<tbody>
<tr>
<td> sf </td> <td> op54 </td><td> 1 1 0 1 1 </td><td> op31 </td><td> Rm </td><td>o0</td><td>Ra</td><td>Rn</td><td>Rd</td>
</tr>
<tr>
<td> 0 </td> <td> 0 0 </td> <td>1 1 0 1 1</td><td> 0 0 0 </td><td> 0 0 0 0 0</td><td>0</td><td>1 1 1 1 1</td><td>0 0 0 1 1</td><td>0 0 1 0 0</td>
</tr>
</tbody>
</table>

You can see that the two registers values we're multiplying are in __Rm__ (__W0__=__00000__) and __Rn__ (__W3__=__00011__) and result goes into __Rd__ (__W4__=__00100__).  The added value would be in the __Ra__
register, but here that is __11111__, which tells the processor to just do the multiply.

OK, let's look at some more instructions, this time things that deal with memory addresses.  Way back in
our first program we saw the instruction __ADR X1, bel__, which loads the address of the data item
labeled __bel__ into register __X1__.  __ADR__ is essentially a variation of an __ADD__ or __SUB__
instruction, where the things being added are the __PC__ (program counter) register and a value
that gives the desired memory address _relative_ to the __PC__.

The hex value of this instruction is __0x100000a1__ or __00010000000000000000000010100001__ in binary.
The instruction format looks like:

<table style="border: 1px solid black;text-align: center;white-space: nowrap; font-family: Courier New,monospace">
<thead style="font-weight: bold;padding: 1 5 1">
<tr>
<td> 31 </td> <td> 30-29 </td><td>28______24</td><td> 23_________________________________5</td><td>4______0</td>
</tr>
</thead>
<tbody>
<tr>
<td> op </td> <td> immlo </td><td> 1 0 0 0 0</td><td> immhi </td><td>Rd</td>
</tr>
<tr>
<td> 0 </td> <td> 0 0 </td> <td>1 0 0 0 0</td><td> 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1</td><td>0 0 0 0 1</td>
</tr>
</tbody>
</table>

This one's a little strange, but basically we tack the __immlo__ bits on to the end of the __immhi__ bits
and we get __10100__ or 20, which happens to be the number of bytes above the current program location
where the __bel__ memory address resides.  So, 20 gets added to the current __PC__ and the result is put
in register __Rd__ (00001).

In the chapter on memory we saw a similar instruction: __ADRP X1, mya1__.  The difference here is that
the value being loaded into the register is not the the exact location of the data, but the _page_ in
memory where that item resides.  Page?  Like books?  Well, kinda.  I'll defer a complete discussion for
now, but recall that I already mentioned that the memory addresses are _virtual_. When the virtual memory
system loads memory it does so in 4KB chunks called _pages_.  As a result, a specific memory address can
be referred to by a page number and an offset within that page.  

The __ADRP__ instruction has the same basic format as the __ADR__ instruction with two exceptions.  First, the leftmost
bit is 1, and second, the immediate value in bits 23 to 5 is the number of pages where the data item
resides relative to the current __PC__ value.  Of course to get the actual byte address, you need
the following instruction that adds the offset within the page.  Since this is a small program and the
data is actually close the data is in the same page as the location where __PC__ points to, so the 22
bits that make up the relative page number are all 0.


<table style="border: 1px solid black;text-align: center;white-space: nowrap; font-family: Courier New,monospace">
<thead style="font-weight: bold;padding: 1 5 1">
<tr>
<td> 31 </td> <td> 30-29 </td><td>28______24</td><td> 23_________________________________5</td><td>4______0</td>
</tr>
</thead>
<tbody>
<tr>
<td> op </td> <td> immlo </td><td> 1 0 0 0 0</td><td> immhi </td><td>Rd</td>
</tr>
<tr>
<td> 1 </td> <td> 0 0 </td> <td>1 0 0 0 0</td><td> 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0</td><td>0 0 0 0 1</td>
</tr>
</tbody>
</table>

Anyway, you get the idea.  Every instruction in the aarch64 instruction is packed into 32 bits, which includes
the operation, immediate values, and registers.  As we'll see these instructions get much more complicated
but they're still 32 bits.  Conceptually the processor loads these instructions into memory and then
executes them in turn (accounting for branching), however as we'll see in future episodes, modern
processors have various ways to make the execution faster, including _pipelining_, operating on multiple
data elements with a single instruction, and predictive branching.

## The Clock

One last note on instructions that connects them to the previous memory episode. As mentioned above the processor goes through a process of fetching the instruction and then executing it, which is called the _fetch-execute_
cycle.  You might wonder what drives the processor to proceed from one instruction to the next.  This
is primarily the function of what's called the _clock_.  The clock isn't really a timekeeper, but rather
a signal that oscillates between a logical 1 and logical 0 value.  The rate at which this happens
is called the _clock speed_, and generally a higher clock speed means a faster processor.  My computer
has a clock speed measured in GHz, while my original PC has a clock speed measured in MHz.

Instructions take some number of clock cycles, however saying precisely _how_ many is complicated by CPU
caching and some of the things mentioned above (eg, pipelining).  As we'll see later on, the clock speed
on my computer is also variable to some degree, which is an energy-saving measure since faster clock speeds
correlate to greater power.  Anyway, it's part of the lingo: instructions and clock cycles are inextricably
linked, and you'll often hear talk of clock speeds and clock cycles when talking about low-level programming
and CPU speed comparisons.


[^1]: Everyone says _opcode_.  It just sounds cooler.